In [1]:
import numpy as np
import joblib

from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.svm import LinearSVC

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

import matplotlib.pyplot as plt
import seaborn as sns

print("Libraries imported successfully!")

Libraries imported successfully!


In [2]:
X_train = np.load("train_features.npy")
X_val = np.load("val_features.npy")
X_test = np.load("test_features.npy")

y_train = np.load("y_train.npy")
y_val = np.load("y_val.npy")
y_test = np.load("y_test.npy")

print("Data loaded successfully!")

Data loaded successfully!


In [3]:
print("X_train:", X_train.shape)
print("X_val:", X_val.shape)
print("X_test:", X_test.shape)

print("y_train:", y_train.shape)
print("y_val:", y_val.shape)
print("y_test:", y_test.shape)

X_train: (122175, 128)
X_val: (26181, 128)
X_test: (26181, 128)
y_train: (122175,)
y_val: (26181,)
y_test: (26181,)


In [4]:
svm_model = Pipeline([
    ("scaler", StandardScaler()),
    ("svm", LinearSVC(
        C=1.0,
        class_weight="balanced",
        max_iter=10000
    ))
])

print("SVM model created!")

SVM model created!


In [5]:
svm_model.fit(X_train, y_train)

print("SVM training completed!")

SVM training completed!


In [6]:
y_val_pred = svm_model.predict(X_val)

print("Validation Accuracy:",
      accuracy_score(y_val, y_val_pred))

print(classification_report(y_val, y_val_pred))

Validation Accuracy: 0.9528665826362629
              precision    recall  f1-score   support

           0       0.94      0.93      0.93      8727
           1       0.96      0.96      0.96      8727
           2       0.96      0.97      0.96      8727

    accuracy                           0.95     26181
   macro avg       0.95      0.95      0.95     26181
weighted avg       0.95      0.95      0.95     26181



In [7]:
y_test_pred = svm_model.predict(X_test)

print("Test Accuracy:",
      accuracy_score(y_test, y_test_pred))

print(classification_report(y_test, y_test_pred))

Test Accuracy: 0.9504220618005423
              precision    recall  f1-score   support

           0       0.94      0.92      0.93      8727
           1       0.96      0.96      0.96      8727
           2       0.96      0.96      0.96      8727

    accuracy                           0.95     26181
   macro avg       0.95      0.95      0.95     26181
weighted avg       0.95      0.95      0.95     26181



In [8]:
cm = confusion_matrix(y_test, y_test_pred)

print(cm)

[[8070  339  318]
 [ 260 8400   67]
 [ 275   39 8413]]


In [9]:
joblib.dump(svm_model, "svm_model1.pkl")

print("svm_model1.pkl saved successfully!")

svm_model1.pkl saved successfully!
